PRODUCT="rootfs_product_centos"
BASE="rootfs_product_base_centos"
HOST="rootfs_host_basic"

LABGW="http://labgw:22222"

URI="tcp://labgw"
NDN="ndn"
APORT="22222"
BPORT="22223"
CPORT="22224"
DPORT="22225"
FPORT="22226"
GPORT="22227"

ALLOC="$URI:$APORT"
BLLOC="$URI:$BPORT"
CLLOC="$URI:$CPORT"
DLLOC="$URI:$DPORT"
FLLOC="$URI:$FPORT"
GLLOC="$URI:$GPORT"
